version: "3.4"

networks:
  public: {}

volumes:
  distbin-db: {}

services:
  distbin:
    build: .
    environment:
    - NODE_DEBUG=distbin
    - LOG_LEVEL=debug
    networks:
    - public
    ports:
    - 80
    volumes:
    - distbin-db:/distbin-db:rw
